### ISSUE TITLE
Rounding

### ISSUE THREAD

**Issue by rafaelsuchy** [OpenSourceEconomics/ekw-data#3]
I think it should be `round(4)` [here](https://github.com/OpenSourceEconomics/ekw-data/blob/78bce4f71c75e5035704ee8dfff48632c27e6b48/struct-data/codes/replication_codes/replication_kw_data.py#L57). In the current state the row normalisation gives 100.1. This is also what KW97 do, but I think we should change to 100.0?

**Comment by peisenha** [comment]
@bekauf  , please address and close.

**Comment by bekauf** [comment]
replication_codes does no longer exist
